parameters:
# Any environment variables to inject into valueFile
#
- name: serviceConnection
  type: string
  displayName: Service Connection to be used to run CLI commands

steps:
# -------------------------------------------------------- #
# Login to Azure CLI                                       #
# -------------------------------------------------------- #

- task: AzureCLI@2
  displayName: az login
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    scriptType: bash
    scriptLocation: inlineScript
    addSpnToEnvironment: true
    inlineScript: |
      set -eu  # fail on error
      subscriptionId=$(az account show --query id -o tsv)
      echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
      echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$servicePrincipalKey"
      echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
      echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"