parameters:
# Any environment variables to inject into valueFile
#
- name: environmentVariables
  type: object
  displayName: Environment Variables for Value File Injection
  default: null

# Working directory where terraform is run (root module)
#
- name: workingDirectory
  displayName: Terraform Root Module Directory
  type: string
  default: $(System.DefaultWorkingDirectory)

steps:
- task: Bash@3
  displayName: Variable injection into config-maps
  env:
    # Loop over any environment varialbes passed in the environmentVariables object
    #
    ${{ each var in parameters.environmentVariables }}:
      ${{ var.key }}: ${{var.value}}
  inputs:
    targetType: 'inline'
    workingDirectory: ${{ parameters.workingDirectory }}
    script: |
      CONFIG_MAPS=`ls ${{ parameters.workingDirectory }}/config-maps`
      echo 'Injecting variables into the following files in ${{ parameters.workingDirectory }}/config-maps:'
      echo "${CONFIG_MAPS[@]}"
      for cm in ${CONFIG_MAPS[@]}; do
        envsubst < ${{ parameters.workingDirectory }}/config-maps/$cm > ${{ parameters.workingDirectory }}/$cm
        cat $cm
      done